name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: repo

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: |
        mkdir results
        cd repo
        sh publishUBL23Docs.sh ../results edge edge now
        find ../results -type f

      #cd repo
      #sh publishUBL23Docs.sh target edge $(date -u +%Y%m%d-%H%Mz) $(date -u +%Y%m%d-%H%Mz)

    - uses: actions/upload-artifact@v2
      with:
        name: hub-UBL-2.3.zip
        path: results/hub-UBL-2.3-*.zip
